trigger: none

variables:
  - group: Build Variables

jobs:
- job:
  displayName: Publish NuGet package
  pool:
    vmImage: windows-2022
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - task: PowerShell@2
    displayName: 'Build and Pack PTF'
    inputs:
      targetType: filePath
      filePath: ./src/build.ps1

  - task: CopyFiles@2
    displayName: 'Copy nupkg to $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: src/drop
      Contents: '*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'