trigger: none 

variables:
  - group: Build Variables

jobs:
- job:
  displayName: Publish NuGet package
  pool: 
    vmImage: windows-2019
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: src/TestFramework/TestFramework.csproj

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: src/TestFramework/TestFramework.csproj
      configuration: '$(build.configuration)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
